### ISSUE TITLE
Add view class tests

### ISSUE THREAD

**Issue by grahamu** [pinax/pinax-images#12]
Verify proper operation of the following view classes:
- `ImageSetUploadView`
  - upload new images and create a new ImageSet.
  - upload images to an existing ImageSet.
- `ImageSetDetailView`
  - get contents of existing ImageSet.
- `ImageDeleteView`
  - delete an Image from an ImageSet. Ensure image is deleted and ImageSet no longer contains that image.
- `ImageTogglePrimaryView`
  - verify image is set/reset as the primary image for an ImageSet.

**Comment by jtauber** [comment]
@paltman try to get done for 16.07 or punt?

**Comment by paltman** [comment]
@jtauber not sure, still trying to get a handle on all my other pings. :)

**Comment by grahamu** [comment]
I'm happy to help with these tests, as it seems `cloudspotting` does not work as intended or expected with current pinax-images. The problem I see is pinax-images views seem to only want to work on `request.user`'s images and image_sets. If that is desired behavior then we need tests proving so, and I don't believe those tests will pass with the current code after accepting PR #3. That PR retained a request.user check in `get_object()`:

```
   def get_object(self, queryset=None):
        return get_object_or_404(self.request.user.image_sets.all(), pk=self.kwargs.get(self.pk_url_kwarg))
```

but failed to make that part of a mixin for use by ImageDeleteView and ImageMakePrimaryView.  As a result these view classes allow manipulation by any authenticated user, which seems completely wrong.

The view classes (and earlier function based views) are missing docstrings so it's difficult to know their intended use. My feeling is permission checking needs to change as follows to make this application more useful:

ImageSetUploadView - user can upload images to their own image_sets. No permission change needed.
ImageSetDetailView - user can view any image from any image_set. Remove restriction of only viewing own images.
ImageDeleteView - user can delete only own images. Change perms to restrict to own image_set image deletion.
ImageTogglePrimaryView - user can only set primary image on own image_sets. Change perms to restrict to own image_set.

**Comment by paltman** [comment]
👍  @grahamu your help would certainly be appreciated and I like your thoughts here.

**Comment by grahamu** [comment]
OK, I'm on it, PR coming soon.
