### ISSUE TITLE
remove recursive-includes in MANIFEST.in

### ISSUE THREAD

**Issue by grahamu** [pinax/pinax-images#17]

**Comment by grahamu** [comment]
static and templates dirs no longer present

**Comment by jtauber** [comment]
@grahamu @paltman should we fix this for 16.07?

**Comment by paltman** [comment]
Does it hurt to just keep them?  They come from our pinax-starter-app template.

**Comment by jtauber** [comment]
Unless it's hurting, I'm inclined to leave it

**Comment by grahamu** [comment]
WFM
